# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/pst.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/pst.proto\"\xb0\x01\n\x0bProtoFolder\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08parentId\x18\x02 \x01(\x05\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x19\n\x11num_of_subfolders\x18\x04 \x01(\x05\x12 \n\nsubfolders\x18\x05 \x03(\x0b\x32\x0c.ProtoFolder\x12\x17\n\x0fnum_of_messages\x18\x06 \x01(\x05\x12\x1f\n\x08messages\x18\x07 \x03(\x0b\x32\r.ProtoMessage\"\xcf\x01\n\x0cProtoMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x13\n\x0bsender_name\x18\x03 \x01(\t\x12\x11\n\thtml_body\x18\x04 \x01(\t\x12\x17\n\x0fplain_text_body\x18\x05 \x01(\t\x12\x19\n\x11transport_headers\x18\x06 \x01(\t\x12\x1f\n\x17\x64\x65livery_time_timestamp\x18\x08 \x01(\x05\x12%\n\x0b\x61ttachments\x18\t \x03(\x0b\x32\x10.ProtoAttachment\"/\n\x0fProtoAttachment\x12\x0c\n\x04size\x18\x01 \x01(\x03\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.pst_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROTOFOLDER']._serialized_start=21
  _globals['_PROTOFOLDER']._serialized_end=197
  _globals['_PROTOMESSAGE']._serialized_start=200
  _globals['_PROTOMESSAGE']._serialized_end=407
  _globals['_PROTOATTACHMENT']._serialized_start=409
  _globals['_PROTOATTACHMENT']._serialized_end=456
# @@protoc_insertion_point(module_scope)
